### ISSUE TITLE
Redirect to phishing site on surl.bz

### ISSUE THREAD

**Issue by dmsagent** [pawy/url_shortener#7]
Hello,

My name is Erika Ulloa, a security analyst with Easy Solutions, Inc.

We recently found that you are Hosting a redirect link targeting one of our clients, a bank in America, in the following URL(s):
 
http://surl.bz/G7Wa9 (Hosted by you)

Which is redirecting to the fraudulent site (phishing site):

http://www.sdhzichlice.cz//libraries/legacy/log/us101.php (Hosted by other company)

The legitimate website is: www.usaa.com 

Please disable these URLs to prevent further fraud to our client, and be sure to gather evidence for a forensics analysis in the event authorities request this information.

For more information about us, please visit www.easysol.net .

Thanks for helping make the Internet safer.

Sincerely, 

Erika Ulloa | DMS Agent
Main: +57-1-7425570 Ext. 192
eulloa@easysol.net | www.easysol.net

**Comment by pawy** [comment]
done
