### ISSUE TITLE
(Critical) URL capturing confidential data using surl.bz  (IP: 80.74.147.43)

### ISSUE THREAD

**Issue by dmsagent** [pawy/url_shortener#8]
Greetings,

This is an official email from Easy Solutions. Please, help us with this issue:

We recently found that you are the Hosting Provider to a URL which is being used to capture confidential data and send it to a remote server. The URL is the following:

http://surl.bz/iG3vR

IP Address: 80.74.147.43

In the following lines, we describe how the attack works.

1. You receive a phishing email with a an attached form. It looks like this:

![image](https://cloud.githubusercontent.com/assets/16430377/13776226/0ad76d80-ea77-11e5-812e-dddb45b7c1cb.png)

2. Then, you fill out the form and make a click on the "Next" button at the end of the form. After that, the information is sent to the URL (the one that you are hosting) using a POST method.

3. When the information is collected, the URL redirects to the affected bank's legitimate URL, in this case https://www.usaa.com/inet/ent_logon/Logon.

Please help us to disable this URL in order to prevent further frauds to the affected bank and get all the evidence for a forensic analysis in case that the authorities ask for it. 

For more information about us, please visit www.easysol.net

Thanks for helping make the Internet safer.

**Comment by pawy** [comment]
done. I added google safe browsing but i seems not to correctly identify fraudulent sites.
